[package]
name = "reedsolomon_ex"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "reedsolomon_ex"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.1"
reed-solomon-simd = { git = "https://github.com/AndersTrier/reed-solomon-simd" }
